### ISSUE TITLE
Ubuntu 15.04: No mails shown in messages indicator

### ISSUE THREAD

**Issue by ghost** [pulb/mailnag-messagingmenu-plugin#1]
_mailnag-unity-plugin 1.1-0~ubuntu15.04.1_

Since upgrading to 15.04 I don't see any new mails in the messages indicator. The icon stays white and no mails are in the list. Mailnag is working, because I receive libnotify notifications.

**Comment by pulb** [comment]
Please run mailnag in a terminal and post the output here.

**Comment by ghost** [comment]
```
$ mailnag
INFO (2015-04-29 18:00:53): Successfully enabled plugin 'libnotifyplugin'.
INFO (2015-04-29 18:00:53): Successfully enabled plugin 'dbusplugin'.
INFO (2015-04-29 18:00:53): Checking 1 email account(s).
```

But, when I click on 'Check for Mail' in the message indicator, I get this:

```
INFO (2015-04-29 18:00:58): Checking 0 email account(s).
```

**Comment by pulb** [comment]
Seems you did not enable the unity plugin in mailnag-config :-)

**Comment by ghost** [comment]
That wasn't listed under plugins. After reinstalling both mailnag (from official Ubuntu repo) and this plugin from your repo, it is. Had to enable it and now it works. 

Thanks for your help.
